### PR TITLE
Added error checking to directed_hausdorf

### PR DESCRIPTION
**Pull request by richardjgowers**
Fixed failing doctest

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Thanks. I may be a bit slow merging it in and there are a bunch of core dev comments to think about now too. I'll try to avoid squashing (at least for now) if possible so you get appropriate credit. They seem to be getting pretty strict about commit formatting these days. At the very least your name is also on the source copyright header.

**Comment by richardjgowers** [comment]
Don't worry about squashing me out of history, I've done about 4 lines to
your hundreds.

**Comment by richardjgowers** [comment]
@tylerjereddy if you want I can try and address the issues from the PR too, I've got a little free time for this

**Comment by tylerjereddy** [comment]
Sure, any help is appreciated!

**Comment by richardjgowers** [comment]
@tylerjereddy I think I've addressed all the comments except 1) why we used this approach and 2) the scaling ie `O(m  * o)`?

**Comment by tylerjereddy** [comment]
Many thanks -- that saves me lots of time.

**Pull request merged**
